// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEHu43I6lZJClNZzS_UFCN2DINoOsulUk',
    appId: '1:830286405620:web:a3d342fa78cac8a7ade3a1',
    messagingSenderId: '830286405620',
    projectId: 'muse0-6debb',
    authDomain: 'muse0-6debb.firebaseapp.com',
    storageBucket: 'muse0-6debb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu96V-8sKlsC15DXgfr6lbNacqkN7Y2_w',
    appId: '1:830286405620:android:c1ec75a5b2fb72dbade3a1',
    messagingSenderId: '830286405620',
    projectId: 'muse0-6debb',
    storageBucket: 'muse0-6debb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAR9Bt63c1YMsq3Jwa4G4YZBOm6OU9Pztg',
    appId: '1:830286405620:ios:a6066eef145cac87ade3a1',
    messagingSenderId: '830286405620',
    projectId: 'muse0-6debb',
    storageBucket: 'muse0-6debb.appspot.com',
    iosBundleId: 'com.example.muse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAR9Bt63c1YMsq3Jwa4G4YZBOm6OU9Pztg',
    appId: '1:830286405620:ios:a6066eef145cac87ade3a1',
    messagingSenderId: '830286405620',
    projectId: 'muse0-6debb',
    storageBucket: 'muse0-6debb.appspot.com',
    iosBundleId: 'com.example.muse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEHu43I6lZJClNZzS_UFCN2DINoOsulUk',
    appId: '1:830286405620:web:58442cd604559c90ade3a1',
    messagingSenderId: '830286405620',
    projectId: 'muse0-6debb',
    authDomain: 'muse0-6debb.firebaseapp.com',
    storageBucket: 'muse0-6debb.appspot.com',
  );
}
